# -*- coding: utf-8 -*-
"""
Created on Fri May 24 23:46:19 2019

@author: amrma
"""

"""ANN

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cqGRYjTD8D5VRektwaWjZOaRwKEXQpyR
"""


import glob # for the path and reeegex
import os
import math
import random
import cv2
import numpy as np
import pandas as pd
#import natsort
  
labelDir= 'E:\dataset\AdelDataset'     # File Dataset Name
labels = os.listdir(labelDir)
newDataDir = 'E:\dataset\AdelImages' # File New Dataset Images
numOfFrames = 3
rate= 2
print('List is :' )
labelcounter = 0

for label in labels:   # Loop in Tokens
    listing = os.listdir(labelDir + '/' + label)
     
    if(len(listing) >= 4 and len(listing) <= 12):    # Check If Token >= 4 Videos
        count = 1
        for file in listing:       # Loop In Videos In Each Token   
            video = cv2.VideoCapture(labelDir + '/' + label + '/' + file)     # Read Video
#             print(video.isOpened())
            # framerate = video.get(5)
            if not os.path.exists(newDataDir + '/' + label + '/' + 'video_' + str(int(count))):      # check if dir Drive/DatasetImages/Token/Video_number Exist
                try:            # If Not Exist Then Create it 
                    os.makedirs( newDataDir + '/' + label + '/' + 'video_' + str(int(count)))
                except OSError as e:
                    if e.errno != errno.EEXIST:
                        raise
            count2 = 1    #Images Counter
            while (video.isOpened()):      # Open Video
                if(count2 > 30 ):          # skip first 2 seconds 
                    frameId = video.get(1)   # Get Frame
                    success,image = video.read()   # Read Frame As Image
                    #print(image)
                    image = np.array(image)       # Convert To Np Array
                    if( image.all() != None ):
                        image=cv2.resize(image,(304,656), interpolation = cv2.INTER_AREA)  # Resize Image
                    if (success != True):
                        break                 # IF Not Image Or Error Then break
                    if (frameId % rate == 0):
                      filename =  newDataDir + '/' + label + '/' + 'video_' + str(int(count)) + '/image_' + str(count2) + '.jpg'     # File Path Of Image of video of Token
#                       print(filename)
                      cv2.imwrite(filename,image)        #create This Image
                count2 +=1
                
            video.release()    # Close This Video 
            print('Done Convert Video_'+ str(int(count)))
            count += 1
            
        labelcounter += 1
        print(str(int(labelcounter)) + '-Done Convert Label: '+ label)
print("Dataset Successfuly Converted")